version: "3.8"

services:
  app:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    image: mongo:6.0.2
    restart: always
    ports:
      - ${DB_PORT}:27017
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db

volumes:
  db:
      

  
