version: "3.8"

services:
  app:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    image: mongo:6.0.2
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db

volumes:
  db:
      

  
